/var/spool/pbs/mom_priv/jobs/5270954.pbs-m1.metacentrum.cz.SC: line 12: .env: No such file or directory
  WARNING: The scripts wandb and wb are installed in '/storage/plzen1/home/takonoselidze/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "main.py", line 221, in <module>
    start(device, generator, deployer, discriminator, attack_type, dataloader, num_epochs)
  File "main.py", line 20, in start
    wandb.init(project='Random Position Patch Attacks', entity='takonoselidze', config={
  File "/storage/plzen1/home/takonoselidze/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
    wandb._sentry.reraise(e)
  File "/storage/plzen1/home/takonoselidze/.local/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/storage/plzen1/home/takonoselidze/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1251, in init
    wi.setup(kwargs)
  File "/storage/plzen1/home/takonoselidze/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 303, in setup
    wandb_login._login(
  File "/storage/plzen1/home/takonoselidze/.local/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/storage/plzen1/home/takonoselidze/.local/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
